sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 13770796063qwe
  alioss:
    endpoint: https://oss-cn-nanjing.aliyuncs.com
    bucket-name: nightwindsss
    access-key-secret: dYtV5DqWvagGCoZluZfbc1aZqXpSNK
    access-key-id: LTAI5t6h8z7dRq63sqyAmgqo
  redis:
    host: localhost
    port: 6379
    password: 13770796063qwe
  wechat:
    appid: wxc1f3737a519202d3
    secret: f8dbdcde0eea97e611df4fa7c000e49d